### ISSUE TITLE
search exception

### ISSUE THREAD

**Issue by amy-why** [jiggy-ai/jiggypedia#5]
File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
--
Thu, Jan 19 2023 7:26:57 pm | pydantic.error_wrappers.ValidationError: 1 validation error for QueryResponse
Thu, Jan 19 2023 7:26:57 pm | token_count
Thu, Jan 19 2023 7:26:57 pm | none is not an allowed value (type=type_error.none.not_allowed)

**Comment by wskish** [comment]
will run the token migration again

**Comment by wskish** [comment]
should be fixed for everything but the 11 embedding entries that are missing sufficient metadata to fix
